version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run build
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
