POST https://localhost:5000/api/user/register HTTP/1.1
content-type: application/json

{
    "username": "usere",
    "fullName": "user e",
    "accountNumber": "0123711777",
    "idNumber": "0123456711882",
    "password": "@User123"
} 


###
POST https://localhost:3000/api/user/login HTTP/1.1
content-type: application/json

{
    "username": "user",
    "accountNumber": "0123756777",
    "idNumber": "0123456788872",
    "password": "@User123"
} 


###
GET  https://localhost:3000/api/payment/6702c11fee71447ffed97d2b HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE3MjgyNTQ0NzYsImV4cCI6MTcyODI1ODA3Nn0.NKf_ijYmUawGbyS9u-E8tfkCJ_R13LELQmcyGmEfbNg


###
POST  https://localhost:3000/api/payment HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE3MjgyNTQ0NzYsImV4cCI6MTcyODI1ODA3Nn0.NKf_ijYmUawGbyS9u-E8tfkCJ_R13LELQmcyGmEfbNg
content-type: application/json

{
    "amount": 2000.00,
    "bankName": "SWIFT",
    "swiftCode": "HSBCGB7G",
    "currency": "ZAR",
    "userId": "6702c11fee71447ffed97d2b"
} 